<?php
$db = new SQLite3('Kisvarda_alallomas_v.trax');
$json = '{"version":0,"comment":{},"transformer":{"windings":[{"index":0,"type":4,"phaseGroup":0,"zero":false,"auto":false,"id":"PRIMARY"},{"index":1,"type":4,"phaseGroup":0,"zero":false,"auto":false,"id":"SECONDARY"}]},"currentTransformer":{"transformers":[{"id":"0","cores":[{"taps":2}]}]},"voltageTransformer":{"transformers":[{"id":"0","sec":[{}]}]},"capacitorVoltageTransformer":{"transformers":[{"id":"0","sec":[{}]}]},"systemInformation":{"tdx":{}},"conditions":{"date":null,"ambientUnit":"celsius","reason":"120kV-os Megszakító Diagnosztika","weather":null,"tester":null,"ambientTemp":0,"humidity":0},"assets":{"asset1Name":"Substation","asset2Name":"Position","asset3Name":"Job #","asset4Name":"Asset ID","asset1":"Kisvárda","asset2":null,"asset3":null,"asset4":null},"labels":[],"recloser":{},"cb":{},"rotatingMachine":{},"measurements":{"cr":[{"settings":{"testCurrent":16,"rampStart":1,"showObjTemp":false,"refTemp":40,"material":0,"r2Current":false,"r2":false,"clamponVA":0.1,"generator":1,"testObjectType":12,"rampFix":10,"continousMode":false},"metaData":{"createdAt":1621545283331,"updatedAt":1621545283331,"weight":1621545283331000,"tags":[{"key":"00","value":"cr"}]},"data":[],"id":"00","comment":{"comment":"40023494, Kisvárda alállomás Atr-R, Megszakító, 1HSB0811072/A1"}},{"settings":{"testCurrent":16,"rampStart":1,"showObjTemp":false,"refTemp":40,"material":0,"r2Current":false,"r2":false,"clamponVA":0.1,"generator":1,"testObjectType":12,"rampFix":10,"continousMode":false},"metaData":{"createdAt":1621545283331,"updatedAt":1621545283331,"weight":1621545283331000,"tags":[{"key":"01","value":"cr"}]},"data":[],"id":"02","comment":{"comment":"40023494, Kisvárda alállomás Atr-R, Megszakító, Piros 1HSB0811072/A1"}},{"settings":{"testCurrent":16,"rampStart":1,"showObjTemp":false,"refTemp":40,"material":0,"r2Current":false,"r2":false,"clamponVA":0.1,"generator":1,"testObjectType":12,"rampFix":10,"continousMode":false},"metaData":{"createdAt":1621545283331,"updatedAt":1621545283331,"weight":1621545283331000,"tags":[{"value":"cr"}]},"data":[],"comment":{"comment":"40023494, Kisvárda alállomás Atr-R, Megszakító, Sárga, 1HSB0811072/A1"}}]}}';
$arr = json_decode($json, true);
$arr["measurements"]["cr"][0]["comment"]["comment"] = "Ezt biza átirtuk PHP-ben. Majd lesz hasznos funkciója is";

$json = json_encode($arr);
$db->exec("CREATE TABLE data (key TEXT PRIMARY KEY, value BLOB)");
$db->exec("INSERT INTO data(key, value) VALUES('trax_json','$json')");
echo $arr["measurements"]["cr"][0]["comment"]["comment"];
?>